backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'public/img' # Media files will be stored in the repo under images/uploads
logo_url: '/public/img/nf-fav.png'
collections:
  - name: 'pages'
    label: 'Pages'
    label_singular: 'Page'
    folder: '_pages/'
    create: true
    editor:
      preview: false
    slug: '{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Contains Subsplash Embed', name: 'subsplash-embed', widget: 'boolean', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
      - label: 'Left Link Block'
        name: 'left_link'
        required: false
        widget: 'relation'
        collection: 'blocks'
        searchFields: ['title', 'link']
        valueField: 'link'
        displayFields: ['title']
      - label: 'Middle Link Block'
        name: 'middle_link'
        required: false
        widget: 'relation'
        collection: 'blocks'
        searchFields: ['title', 'link']
        valueField: 'link'
        displayFields: ['title']
      - label: 'Right Link Block'
        name: 'right_link'
        required: false
        widget: 'relation'
        collection: 'blocks'
        searchFields: ['title', 'link']
        valueField: 'link'
        displayFields: ['title']
  - name: 'blocks'
    label: 'Link Blocks'
    label_singular: 'Link Block'
    folder: '_blocks/'
    create: true
    editor:
      preview: false
    slug: '{{slug}}'
    fields:
      - label: 'Layout'
        name: 'style'
        widget: 'select'
        options:
          - { label: 'Background Image', value: 'image-block' }
          - { label: 'Custom Subsplash Embed', value: 'custom-embed' }
          - { label: 'Solid Black', value: 'solid-black' }
      - {label: 'Text', name: title, widget: string}
      - {label: 'Image', name: image, widget: image, required: false}
      - {label: 'Link', name: 'link', widget: string, default: 'example.html'}
  - name: 'nav'
    label: 'Navigation'
    editor:
      preview: false
    files:
      - label: 'Top Navigation Menu'
        name: 'navigation'
        file: '_data/navigation.yml'
        fields:
          - label: 'Navigation Groups'
            name: 'groups'
            widget: 'list'
            allow_add: false
            fields:
              - {label: 'Group Heading', name: 'title', widget: 'string'}
              - label: 'Pages'
                singular_label: 'Page'
                name: 'pages'
                widget: 'list'
                fields:
                  - {label: 'Name', name: 'title', widget: string}
                  - {label: 'Link', name: 'url', widget: string, default: '/example.html'}
