backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'public/img' # Media files will be stored in the repo under images/uploads
logo_url: '/public/img/nf-fav.png'
collections:
  - name: 'pages'
    label: 'Pages'
    folder: '_pages/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Contains Subsplash Embed', name: 'subsplash-embed', widget: 'boolean' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Left Block'
        name: 'left_link'
        widget: 'relation'
        collection: 'links'
        searchFields: ['text', 'link']
        valueField: 'link'
        displayFields: ['text']
      - label: 'Middle Block'
        name: 'middle_link'
        widget: 'relation'
        collection: 'links'
        searchFields: ['text', 'link']
        valueField: 'link'
        displayFields: ['text']
      - label: 'Right Block'
        name: 'right_link'
        widget: 'relation'
        collection: 'links'
        searchFields: ['text', 'link']
        valueField: 'link'
        displayFields: ['text']
  - name: 'config'
    label: 'Configuration'
    editor:
      preview: false
    files:
      - label: 'Top Navigation'
        name: 'navigation'
        file: '_data/navigation.yml'
        fields:
          - label: 'Navigation Items'
            name: 'groups'
            widget: 'list'
            allow_add: false
            fields:
              - {label: 'Group Heading', name: 'title', widget: 'string'}
              - label: 'Pages'
                name: 'pages'
                widget: 'list'
                fields:
                  - {label: 'Name', name: 'title', widget: string}
                  - {label: 'Link', name: 'url', widget: string, default: '/example.html'}
      - label: 'Link Blocks'
        name: 'link-blocks'
        file: '_data/links.yml'
        fields:
          - label: 'Layout'
            name: 'layout'
            widget: 'select'
            options:
              - { label: 'Background Image', value: 'image-block' }
              - { label: 'Custom Subsplash Embed', value: 'custom-embed' }
              - { label: 'Solid Black', value: 'solid-black' }
          - {label: 'Text', name: text, widget: string}
          - {label: 'Image', name: image, widget: image}
          - label: 'Linked Page'
            name: 'link'
            widget: 'relation'
            collection: 'pages'
            searchFields: ['title', 'url']
            valueField: 'url'
            displayFields: ['title']
