backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'public/img' # Media files will be stored in the repo under images/uploads
logo_url: '/public/img/nf-fav.png'
collections:
  - name: 'pages'
    label: 'Pages'
    folder: '_pages/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Contains Subsplash Embed', name: 'subsplash-embed', widget: 'boolean' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Left Link', name: 'left_link', widget: 'string', default: 'example.html' }
      - { label: 'Middle Link', name: 'middle_link', widget: 'string', default: 'example.html' }
      - { label: 'Right Link', name: 'right_link', widget: 'string', default: 'example.html' }
  - name: 'config'
    label: 'Configuration'
    editor:
      preview: false
    files:
      - label: 'Top Navigation'
        name: 'navigation'
        file: '_data/navigation.yml'
        fields:
          - label: 'Navigation Groups'
            name: 'groups'
            widget: 'list'
            allow_add: false
            fields:
              - {label: 'Group Heading', name: 'title', widget: 'string'}
              - label: 'Pages'
                singular_label: 'Page'
                name: 'pages'
                widget: 'list'
                fields:
                  - {label: 'Name', name: 'title', widget: string}
                  - {label: 'Link', name: 'url', widget: string, default: '/example.html'}
      - label: 'Link Blocks'
        name: 'links'
        file: '_data/links.yml'
        fields:
          - label: 'Link Blocks'
            name: 'blocks'
            widget: 'list'
            fields:
              - label: 'Layout'
                name: 'layout'
                widget: 'select'
                options:
                  - { label: 'Background Image', value: 'image-block' }
                  - { label: 'Custom Subsplash Embed', value: 'custom-embed' }
                  - { label: 'Solid Black', value: 'solid-black' }
              - {label: 'Text', name: title, widget: string}
              - {label: 'Image', name: image, widget: image}
              - {label: 'Link', name: 'link', widget: string, default: 'example.html'}
